AWSTemplateFormatVersion: '2010-09-09'
Description: This template deploys a cloudwatch event, sns topic and lambda function in order to send AWS health alerts to a slack channel
Parameters:
  Key:
    Description: Key for taging 
    Type: String
  Value:
    Description: Value for the tag Key
    Type: String
  SlackChannel:
    Description: Name of the Channel where you want the alerts to be display
    Type: String
  WebHook:
    Description: Slack's incoming webhook URL 
    Type: String

Resources:

  Security:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: infra/infra.yaml
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        Key: !Ref Key
        Value: !Ref Value

  EventAndTopic:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: EventAndTopic/EventAndTopic.yaml
      Parameters:
        EnvironmentName: !Ref AWS::StackName

  LambdaFunction:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: lambda/lambda.yaml
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        Role: !GetAtt Security.Outputs.Role
        KmsKey: !GetAtt Security.Outputs.Key
        SNSTopic: !GetAtt EventAndTopic.Outputs.SNSArn
        SlackChannel: !Ref SlackChannel
        WebHook: !Ref WebHook